/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as KelolaBookingRouteImport } from './routes/kelola-booking'
import { Route as KonfirmasiRouteImport } from './routes/konfirmasi'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as ProdukIdRouteImport } from './routes/produk.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const KelolaBookingRoute = KelolaBookingRouteImport.update({
  id: '/kelola-booking',
  path: '/kelola-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfirmasiRoute = KonfirmasiRouteImport.update({
  id: '/konfirmasi',
  path: '/konfirmasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/produk/$id',
  path: '/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/jadwal': typeof JadwalRoute
  '/katalog': typeof KatalogRoute
  '/kelola-booking': typeof KelolaBookingRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/kontak': typeof KontakRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/jadwal': typeof JadwalRoute
  '/katalog': typeof KatalogRoute
  '/kelola-booking': typeof KelolaBookingRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/kontak': typeof KontakRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/jadwal': typeof JadwalRoute
  '/katalog': typeof KatalogRoute
  '/kelola-booking': typeof KelolaBookingRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/kontak': typeof KontakRoute
  '/produk/$id': typeof ProdukIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/jadwal'
    | '/katalog'
    | '/kelola-booking'
    | '/konfirmasi'
    | '/kontak'
    | '/produk/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/booking'
    | '/jadwal'
    | '/katalog'
    | '/kelola-booking'
    | '/konfirmasi'
    | '/kontak'
    | '/produk/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/jadwal'
    | '/katalog'
    | '/kelola-booking'
    | '/konfirmasi'
    | '/kontak'
    | '/produk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  JadwalRoute: typeof JadwalRoute
  KatalogRoute: typeof KatalogRoute
  KelolaBookingRoute: typeof KelolaBookingRoute
  KonfirmasiRoute: typeof KonfirmasiRoute
  KontakRoute: typeof KontakRoute
  ProdukIdRoute: typeof ProdukIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelola-booking': {
      id: '/kelola-booking'
      path: '/kelola-booking'
      fullPath: '/kelola-booking'
      preLoaderRoute: typeof KelolaBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfirmasi': {
      id: '/konfirmasi'
      path: '/konfirmasi'
      fullPath: '/konfirmasi'
      preLoaderRoute: typeof KonfirmasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/produk/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  JadwalRoute: JadwalRoute,
  KatalogRoute: KatalogRoute,
  KelolaBookingRoute: KelolaBookingRoute,
  KonfirmasiRoute: KonfirmasiRoute,
  KontakRoute: KontakRoute,
  ProdukIdRoute: ProdukIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
